GET http://localhost:8080/users/Home
#  Content-Type: "application/json"
###
//Get offered bikes and scooters
GET http://localhost:8080/users/my-biscooter/1  HTTP/1.1




###
#Feedback
POST http://localhost:8080/users/ClientActions5/1  HTTP/1.1
Content-Type: application/json

{
        "RATING":"5",
        "DATE":"2005-10-4",
        "DESCRIPTION":"Very good",
        "BISCOOT_ID":"300"
}

###

#Complaint
POST http://localhost:8080/users/ClientActions6/1 HTTP/1.1
Content-Type: application/json

{
        "DATE":"2-10-2008",
        "DESCRIPTION":"whawt the fa",
        "TYPE":"ON SCOOTER"
}


###

#Transaction
POST http://localhost:8080/users/Transactions/8  HTTP/1.1
Content-Type: application/json

{
        "CARDOTP":"275225",
        "STATUS":"Deposit",
        "AMOUNT":"20",
        "DATE":"2005-9-10"
}
###
//RESERVING
POST http://localhost:8080/users/ClientActions1/1  HTTP/1.1
Content-Type: application/json

{
        "COST":"20",
        "STATUS":"Deposit",
        "DATE_OF_RENTAL":"2023-5-12",
        "DURATION":"50",
        "KICKOFF_STATION_ID":"1",
        "DISTINATION_STATION_ID":"2",
        "BISCOOT_ID":"50"
}
###
POST http://localhost:8080/users/ClientActions2  HTTP/1.1
Content-Type: application/json

{
       "ID":"3"
}
###
//Offer Bike
POST http://localhost:8080/users/offer/bike/1  HTTP/1.1
Content-Type: application/json

{
  "TYPE_OF_BIKE":"RACE",
   "GEARS_NUM":"20"	,
   "BRAND":"NOKIA"	,
   "WEIGHT":"15"	,
  "SIZE":"55"
}
###
//Offer Scooter

POST http://localhost:8080/users/offer/scooter/1  HTTP/1.1
Content-Type: application/json

{
  "BATTERY_CAPACITY":"500",
   "RANGE":"20"	,
   "MAX_SPEED":"15"	,
  "SIZE":"55"
}

###

POST http://localhost:8080/users/ClientActions4/RemoveScooter/1  HTTP/1.1
Content-Type: application/json

{
"SCOOTER_ID":"1"
}


###
POST http://localhost:8080/users/ClientActions4/RemoveBike/1  HTTP/1.1
Content-Type: application/json

{
 "BIKE_ID":"1"
}


###
//Admin ViewAll
GET http://localhost:8080/admin/ViewAll  HTTP/1.1



###
//ADD EMPLOYEE
POST http://localhost:8080/admin/AddEmployee  HTTP/1.1
Content-Type: application/json

{
        "NATIONAL_ID":"1265"	,														
	"USERNAME":"Peter",		
	"TELEPHONE":"0125664"	,
	"EMAIL"	:"puyfl@gmail.com",		
	"PASSWORD":"ppppppp"	,	
	"SALARY":"9787"	,		
	"BIRTHDATE":"2005-8-8",
	"FNAME"	:"Peter",		
	"MNAME":"kjhh",			
	"LNAME"	:"uhuuh",		
	"MGR_ID":"125",
	"STATION_ID":"1"

}
###
//ADD SUPPLIER
POST http://localhost:8080/admin/AddSupplier  HTTP/1.1
Content-Type: application/json

{				
	"EMAIL":"peter@gmail.com",			
	"PHONE_NUMBER":"136656",	
	"FNAME":"pyuyu",			
	"MNAME"	:"kjhh",		
	"LNAME"	:"jhuhu"		
}
###
//ADD ADMIN

POST http://localhost:8080/admin/AddAdmin  HTTP/1.1
Content-Type: application/json

{
        "NATIONAL_ID":"125"	,														
	"USERNAME":"Peter",		
	"TELEPHONE":"0125664"	,
	"EMAIL"	:"puyfl@hotmail.com",		
	"PASSWORD":"ppppppp"	,	
	"SALARY":"9787"	,		
	"BIRTHDATE":"2005-8-8",
	"FNAME"	:"Peter",		
	"MNAME":"kjhh",			
	"LNAME"	:"uhuuh",		
	"STATION_ID":"1"

}

###
//DROP ADMIN
POST http://localhost:8080/admin/DropAdmin  HTTP/1.1
Content-Type: application/json

{
     "ADMIN_ID":"125"
}
###
//DROP ADMIN
POST http://localhost:8080/admin/DropAdmin  HTTP/1.1
Content-Type: application/json

{
     "ADMIN_ID":"125"
}
###
//DROP EMPLOYEE
POST http://localhost:8080/admin/DropEmployee  HTTP/1.1
Content-Type: application/json

{
     "NATIONAL_ID":"125"
}
###
//DROP ADMIN
POST http://localhost:8080/admin/DropClient  HTTP/1.1
Content-Type: application/json

{
     "ID":"1"
}
###
//DROP SUPPLIER
POST http://localhost:8080/admin/DropSupplier  HTTP/1.1
Content-Type: application/json

{
     "ID":"33"
}

###
//ADMIN SIGN UP
POST http://localhost:8080/admin/signup  HTTP/1.1
Content-Type: application/json

{
        "NATIONAL_ID":"125"	,														
	"USERNAME":"Peter",		
	"TELEPHONE":"0125664"	,
	"EMAIL"	:"puyfl@hotmail.com",		
	"PASSWORD":"ppppppp"	,	
	"SALARY":"9787"	,		
	"BIRTHDATE":"2005-8-8",
	"FNAME"	:"Peter",		
	"MNAME":"kjhh",			
	"LNAME"	:"uhuuh",		
	"STATION_ID":"1"

}
###
//ADMIN LOG IN
POST http://localhost:8080/admin/login  HTTP/1.1
Content-Type: application/json

{
     
	"email"	:"puyfl@hotmail.com",		
	"password":"ppppppp"	
}



###
//ADD CLIENT
POST http://localhost:8080/admin/AddClient  HTTP/1.1
Content-Type: application/json

{
   "FName":"Peter",
   "MName":"Safwat",
   "LName":"Sahyon",
   "Email":"peterysKafwi9bk@gmail.com",
   "Username":"PeteyK86199",
   "Telephone":"0100677697129",
   "Password":"pppppppp"
}



###
//LOG IN CLIENT
POST http://localhost:8080/auth/login  HTTP/1.1
Content-Type: application/json

{
   "email":"peterLsafwathbk@gmail.com", 
   "password":"pppppppp"
}


###
GET http://localhost:8080/auth/me/1

###
//LOG IN CLIENT
POST http://localhost:8080/users/changeProfileImage/1
Content-Type: application/json

{
   "img_url": "there"
}

###
DELETE http://localhost:8080/users/my-biscooter/drop/1

###
GET http://localhost:8080/users/complaints/1