CREATE database SCHEMA_DB
USE SCHEMA_DB
Go

CREATE TABLE CLIENT 
(
	ID				INT													PRIMARY KEY,
	CARD_ID			INT						NOT NULL					UNIQUE,
	EMAIL			NVARCHAR(100)			NOT NULL					UNIQUE,
	USERNAME		NVARCHAR(50)			NOT NULL					UNIQUE,
	TELEPHONE		VARCHAR(15)				NOT NULL					UNIQUE,
	INVITATION_CODE VARCHAR(8)											UNIQUE,
	FNAME			VARCHAR(20)				NOT NULL,	
	MNAME			VARCHAR(20)				NOT NULL,
	LNAME			VARCHAR(20)				NOT NULL,
	PASSWORD		NVARCHAR(256)			NOT NULL,
	STATUS			VARCHAR(20),										-- Renter/Owner	
	WALLET			MONEY,
	INVITED_CLIENT	INT													FOREIGN KEY REFERENCES CLIENT,
);

CREATE TABLE STATION
(
	ID				INT													PRIMARY KEY,
	CITY			VARCHAR(50),
	STREET			VARCHAR(50),
	ZIP				INT,
																		CONSTRAINT ADDRESS UNIQUE (CITY,STREET,ZIP),
	NAME			VARCHAR(50)											UNIQUE
);

CREATE TABLE SHIPMENT
(
	ID				  INT												PRIMARY KEY,
	DELIVERY_DATE	  DATE					NOT NULL,
	DEADLINE_DATE	  DATE					NOT NULL,
	COST			  INT					NOT NULL,
	BIKES_AMOUNT      VARCHAR(20),
	SCOOTERS_AMOUNT	  VARCHAR(20)
);

CREATE TABLE BISCOOT
(
    ID				INT													PRIMARY KEY,
    RNT_COST		INT						NOT NULL,
    SIZE			INT						NOT NULL,
    LAST_MNT_DATA	INT						NOT NULL,
    PRICE			INT						NOT NULL,
    IMAGE			VARCHAR(256)			NOT NULL,
	OWNER_ID		INT													FOREIGN KEY REFERENCES CLIENT,
	STATION_ID		INT						NOT NULL					FOREIGN KEY REFERENCES STATION,
	SHIPMENT_ID		INT						NOT NULL					FOREIGN KEY REFERENCES SHIPMENT
);

CREATE TABLE TRANS_ACTION
(
	ID				INT													PRIMARY KEY,
	CARDOTP			INT						NOT NULL					UNIQUE,
	STATUS			VARCHAR(20)				NOT NULL,					-- Deposit/Withdraw
	AMOUNT			INT						NOT NULL,
	DATE			DATE					NOT NULL,
	CLIENT_ID		INT						NOT NULL					FOREIGN KEY REFERENCES CLIENT
);




CREATE TABLE FEEDBACK
(
	ID				INT													PRIMARY KEY,
	RATING			INT						NOT NULL,
	DATE			DATE					NOT NULL,
	DESCRIPTION		NVARCHAR(256),
	BISCOOT_ID		INT													FOREIGN KEY REFERENCES BISCOOT	
);

CREATE TABLE SUPPLIER
(
	ID				INT													PRIMARY KEY,
	EMAIL			NVARCHAR(256)			NOT NULL					UNIQUE,
	PHONENUMBER		VARCHAR(20)				NOT NULL					UNIQUE,
	FNAME			VARCHAR(20)				NOT NULL,
	MNAME			VARCHAR(20)				NOT NULL,
	LNAME			VARCHAR(20)				NOT NULL
);

CREATE TABLE EMPLOYEE
(
	NATIONAL_ID		INT													PRIMARY KEY,
	USERNAME		NVARCHAR(50)										UNIQUE,
	TELEPHONE		VARCHAR(15)				NOT NULL					UNIQUE,
	EMAIL			NVARCHAR(100)			NOT NULL					UNIQUE,
	PASSWORD		NVARCHAR(256)			NOT NULL,
	SALARY			INT,
	BIRTHDAY		DATE					NOT NULL,
	FNAME			VARCHAR(20)				NOT NULL,
	MNAME			VARCHAR(20)				NOT NULL,
	LNAME			VARCHAR(20)				NOT NULL,
	MGR_ID			INT						NOT NULL					FOREIGN KEY REFERENCES EMPLOYEE,
	STATION_ID		INT													FOREIGN KEY REFERENCES STATION
);
 
CREATE TABLE COMPLAINT
(
	ID				INT													PRIMARY KEY,
	DATE			DATE,
	DESCRIPTION		NVARCHAR(256),
	STATUS			VARCHAR(20)				NOT NULL,					-- Responded/Pending Complaint
	TYPE			VARCHAR(20)				NOT NULL,					--	Complaint to be OnBike/OnScooter 
	CLIENT_ID		INT						NOT NULL					FOREIGN KEY REFERENCES CLIENT,
	EMPLOYEE_ID		INT						NOT NULL					FOREIGN KEY REFERENCES EMPLOYEE
);

CREATE TABLE ADMIN
(
	ADMIN_ID INT PRIMARY KEY ,
	FOREIGN KEY(ADMIN_ID) REFERENCES EMPLOYEE
);

CREATE TABLE RENTALS
(
    ID						INT											PRIMARY KEY,
    COST					MONEY			NOT NULL,
    STATUS					VARCHAR(50),
    DATE_OF_RENTAL			DATE			NOT NULL,
    DURATION				INT				NOT NULL,
	KICKOFF_STATION_ID		INT				NOT NULL					FOREIGN KEY REFERENCES STATION,
	DISTINATION_STATION_ID  INT				NOT NULL					FOREIGN KEY REFERENCES STATION	
);

CREATE TABLE BIKE
(
	TYPE_OF_BIKE		VARCHAR(50)			NOT NULL,
	GEARS_NUM			INT					NOT NULL,
	BRAND				VARCHAR(50)			NOT NULL ,
	WEIGHT				INT					NOT NULL,
	BIKE_ID				INT												PRIMARY KEY,
																		FOREIGN KEY (BIKE_ID) REFERENCES BISCOOT (ID)
)

CREATE TABLE SCOOTER
(
	BATTERY_CAPACITY	VARCHAR(20)			NOT NULL,
	RANGE				INT					NOT NULL,
	MAX_SPEED			INT					NOT NULL,
	SCOOTER_ID			INT												PRIMARY KEY,
																		FOREIGN KEY (SCOOTER_ID) REFERENCES BISCOOT (ID)
);

CREATE TABLE MAINTAINENCE
(
    ID					INT												PRIMARY KEY,
    TYPE_OF_MNT			VARCHAR(50)			NOT NULL ,
    DATE_OF_MNT			DATE				NOT NULL,
    DESCRIPTION			VARCHAR(256)		NOT NULL,
    COST				MONEY				NOT NULL,
    STATUS				VARCHAR(50)			NOT NULL
)

CREATE TABLE RENT_BISCOOT
(
	RENTAL_ID			INT												PRIMARY KEY,
																		FOREIGN KEY(RENTAL_ID) REFERENCES RENTALS,
	CLIENT_ID			INT												FOREIGN KEY	REFERENCES CLIENT,
	BISCOOT_ID			INT												FOREIGN KEY REFERENCES BISCOOT	 
);

CREATE TABLE CONDUCT_MAINTAINENCE
(
	MNT_ID			    INT												PRIMARY KEY,
																		FOREIGN KEY (MNT_ID) REFERENCES MAINTAINENCE,
	EMPLOYEE_ID			INT												FOREIGN KEY REFERENCES EMPLOYEE,
	BISCOOT_ID		    INT												FOREIGN KEY REFERENCES BISCOOT
);	

CREATE TABLE SHIPMENT_ORDER
(
	SHIPMENT_ID			INT												PRIMARY KEY,
																		FOREIGN KEY(SHIPMENT_ID) REFERENCES SHIPMENT,
	EMPLOYEE_ID			INT												FOREIGN KEY REFERENCES EMPLOYEE,
	SUPPLIER_ID		    INT					NOT NULL					FOREIGN KEY	REFERENCES SUPPLIER
);

CREATE TABLE FEEDBACK_BISCOOT
(
	FEEDBACK_ID			INT												PRIMARY KEY,
																		FOREIGN KEY(FEEDBACK_ID) REFERENCES FEEDBACK,
	CLIENT_ID			INT												FOREIGN KEY	REFERENCES CLIENT,
	BISCOOT_ID			INT												FOREIGN KEY REFERENCES BISCOOT
);

CREATE TABLE BIKES_NUMBERS
(
	STATION_ID			INT												PRIMARY KEY,
																		FOREIGN KEY(STATION_ID) REFERENCES STATION,
	NUM					INT												
);

CREATE TABLE SCOOTERS_NUMBERS
(
	STATION_ID			INT												PRIMARY KEY,
																		FOREIGN KEY(STATION_ID) REFERENCES STATION,
	NUM					INT												
);




GO
CREATE TRIGGER COUNT_BIKES
ON STATION
AFTER INSERT,UPDATE,DELETE
AS
BEGIN
    UPDATE BIKES_NUMBERS
	SET NUM = (SELECT COUNT(*)
	  FROM BISCOOT ,BIKE ,STATION
	  WHERE BISCOOT.ID = BIKE.BIKE_ID AND BISCOOT.STATION_ID = STATION.ID AND STATION.ID = BIKES_NUMBERS.STATION_ID)
END;

GO
CREATE TRIGGER COUNT_SCOOTERS
ON STATION
AFTER INSERT,UPDATE,DELETE
AS
BEGIN
    UPDATE SCOOTERS_NUMBERS
	SET NUM = (SELECT COUNT(*)
	  FROM BISCOOT ,SCOOTER ,STATION
	  WHERE BISCOOT.ID = SCOOTER.SCOOTER_ID AND BISCOOT.STATION_ID = STATION.ID AND STATION.ID = SCOOTERS_NUMBERS.STATION_ID)
END;
GO